spring:
  application:
    name: EventClean

  datasource:
#    url: jdbc:postgresql://localhost:5432/eventclean
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
#    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enable: true
      path: /h2-console

  jpa:
#    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    flyway:
      enable: true
      locations: classpath:db/migration
